import os

from mods.yolox_meta_food_2026 import Exp as MyExp
from mods.sup_contrastive_loss import SupervisedContrastiveLoss


class Exp(MyExp):

    def __init__(self):
        super().__init__()
        self.num_classes = 37

        sup_contrastive_loss = SupervisedContrastiveLoss()  # temperature=0.07

        self.cls_feat_loss = sup_contrastive_loss
        self.cls_feat_weight = 0

        self.exp_name = os.path.split(os.path.realpath(__file__))[1].split(".")[0]
        self.exp_name = f"{self.exp_name}_baseline"

        # ---------------- dataloader config ---------------- #

        # Define yourself dataset path
        self.data_dir = "datasets/CAFSD"
        self.train_ann = "annotation_train.json"
        self.val_ann = "annotation_test.json"

        # --------------  training config --------------------- #

        self.max_epoch = 2  # 100
        self.data_num_workers = 4
        self.eval_interval = 1

        # ---------------- semmel config ---------------- #

        self.num_classes = 239
        self.names = {
            1: 'achichuk',
            2: 'airan-katyk',
            3: 'almond',
            4: 'apple',
            5: 'apricot',
            6: 'artichoke',
            7: 'arugula',
            8: 'asip',
            9: 'asparagus',
            10: 'avocado',
            11: 'bacon',
            12: 'baklava',
            13: 'banana',
            14: 'basil',
            15: 'bauyrsak',
            16: 'bean soup',
            17: 'beans',
            18: 'beef shashlyk',
            19: 'beef shashlyk-v',
            20: 'beer',
            21: 'beet',
            22: 'bell pepper',
            23: 'beshbarmak',
            24: 'beverages',
            25: 'black olives',
            26: 'blackberry',
            27: 'blueberry',
            28: 'boiled chicken',
            29: 'boiled eggs',
            30: 'boiled meat',
            31: 'borsch',
            32: 'bread',
            33: 'brizol',
            34: 'broccoli',
            35: 'buckwheat',
            36: 'butter',
            37: 'cabbage',
            38: 'cakes',
            39: 'carrot',
            40: 'cashew',
            41: 'casserole with meat and vegetables',
            42: 'cauliflower',
            43: 'caviar',
            44: 'celery',
            45: 'cereal based cooked food',
            46: 'chak-chak',
            47: 'cheburek',
            48: 'cheese',
            49: 'cheese souce',
            50: 'cherry',
            51: 'chestnuts',
            52: 'chicken shashlyk',
            53: 'chicken shashlyk-v',
            54: 'chickpeas',
            55: 'chili pepper',
            56: 'chips',
            57: 'chocolate',
            58: 'chocolate paste',
            59: 'cinnabons',
            60: 'coffee',
            61: 'condensed milk',
            62: 'cooked eggplant',
            63: 'cooked food based on meat',
            64: 'cooked food meat with vegetables',
            65: 'cooked tomatoes',
            66: 'cooked zucchini',
            67: 'cookies',
            68: 'corn',
            69: 'corn flakes',
            70: 'crepe',
            71: 'crepe w filling',
            72: 'croissant',
            73: 'croissant sandwich',
            74: 'cucumber',
            75: 'cutlet',
            76: 'dates',
            77: 'desserts',
            78: 'dill',
            79: 'doner-lavash',
            80: 'doner-nan',
            81: 'dragon fruit',
            82: 'dried fruits',
            83: 'egg product',
            84: 'eggplant',
            85: 'figs',
            86: 'fish',
            87: 'french fries',
            88: 'fried cheese',
            89: 'fried chicken',
            90: 'fried eggs',
            91: 'fried fish',
            92: 'fried meat',
            93: 'fruits',
            94: 'garlic',
            95: 'granola',
            96: 'grapefruit',
            97: 'grapes',
            98: 'green beans',
            99: 'green olives',
            100: 'hachapuri',
            101: 'hamburger',
            102: 'hazelnut',
            103: 'herbs',
            104: 'hinkali',
            105: 'honey',
            106: 'hot dog',
            107: 'hummus',
            108: 'hvorost',
            109: 'ice-cream',
            110: 'irimshik',
            111: 'jam',
            112: 'juice',
            113: 'karta',
            114: 'kattama-nan',
            115: 'kazy-karta',
            116: 'ketchup',
            117: 'kiwi',
            118: 'kurt',
            119: 'kuyrdak',
            120: 'kymyz-kymyran',
            121: 'lagman-fried',
            122: 'lagman-w-soup',
            123: 'lavash',
            124: 'legumes',
            125: 'lemon',
            126: 'lime',
            127: 'mandarin',
            128: 'mango',
            129: 'manty',
            130: 'mashed potato',
            131: 'mayonnaise',
            132: 'meat based soup',
            133: 'meat product',
            134: 'melon',
            135: 'milk',
            136: 'minced meat shashlyk',
            137: 'mint',
            138: 'mixed berries',
            139: 'mixed nuts',
            140: 'muffin',
            141: 'mushrooms',
            142: 'naryn',
            143: 'nauryz-kozhe',
            144: 'noodles soup',
            145: 'nuggets',
            146: 'oil',
            147: 'okra',
            148: 'okroshka',
            149: 'olivie',
            150: 'onion',
            151: 'onion rings',
            152: 'orama',
            153: 'orange',
            154: 'pancakes',
            155: 'parsley',
            156: 'pasta',
            157: 'pastry',
            158: 'peach',
            159: 'peanut',
            160: 'pear',
            161: 'peas',
            162: 'pecan',
            163: 'persimmon',
            164: 'pickled cabbage',
            165: 'pickled cucumber',
            166: 'pickled ginger',
            167: 'pickled squash',
            168: 'pie',
            169: 'pineapple',
            170: 'pistachio',
            171: 'pizza',
            172: 'plov',
            173: 'plum',
            174: 'pomegranate',
            175: 'porridge',
            176: 'potatoes',
            177: 'pumpkin',
            178: 'pumpkin seeds',
            179: 'quince',
            180: 'radish',
            181: 'raspberry',
            182: 'redcurrant',
            183: 'ribs',
            184: 'rice',
            185: 'rosemary',
            186: 'salad fresh',
            187: 'salad leaves',
            188: 'salad with fried meat veggie',
            189: 'salad with sauce',
            190: 'samsa',
            191: 'sandwich',
            192: 'sausages',
            193: 'scallion',
            194: 'seafood',
            195: 'seafood soup',
            196: 'sheep-head',
            197: 'shelpek',
            198: 'shorpa',
            199: 'shorpa chicken',
            200: 'smetana',
            201: 'smoked fish',
            202: 'snacks',
            203: 'snacks bread',
            204: 'soda',
            205: 'souces',
            206: 'soup-plain',
            207: 'soy souce',
            208: 'spinach',
            209: 'spirits',
            210: 'strawberry',
            211: 'sugar',
            212: 'sushi',
            213: 'sushi fish',
            214: 'sushi nori',
            215: 'sushki',
            216: 'suzbe',
            217: 'sweets',
            218: 'syrniki',
            219: 'taba-nan',
            220: 'talkan-zhent',
            221: 'tartar',
            222: 'tea',
            223: 'tomato',
            224: 'tomato souce',
            225: 'tomato-cucumber-salad',
            226: 'tushpara-fried',
            227: 'tushpara-w-soup',
            228: 'tushpara-wo-soup',
            229: 'vareniki',
            230: 'vegetable based cooked food',
            231: 'vegetable soup',
            232: 'waffles',
            233: 'walnut',
            234: 'wasabi',
            235: 'water',
            236: 'watermelon',
            237: 'wine',
            238: 'wings',
            239: 'zucchini',
        }
        self.img_size = (640, 640)  # (height, width)

        # ---------------- model config ---------------- #

        scale = "yolox_x"  # "yolox_m" # "yolox_l" # "yolox_x"

        if scale == "yolox_s":
            self.depth = 0.33
            self.width = 0.50
        if scale == "yolox_m":
            self.depth = 0.67
            self.width = 0.75
        if scale == "yolox_l":
            self.depth = 1.0
            self.width = 1.0
        if scale == "yolox_x":
            self.depth = 1.33
            self.width = 1.25

        # self.ckpt = f"checkpoints/{scale}.pth"
