names_brezel = {
    1: "Brezel",
}

names_04 = {
    1: "Backware",
    2: "Bauernbrot",
    3: "Floesserbrot",
    4: "Salzstange",
    5: "Sonnenblumensemmel",
    6: "Kuerbiskernsemmel",
    7: "Roggensemmel",
    8: "Dinkelsemmel",
    9: "LaugenstangeSchinkenKaese",
    10: "Pfefferlaugenbrezel",
    11: "KernigeStange",
    12: "Schokocroissant",
    13: "Apfeltasche",
    14: "Quarktasche",
    15: "Mohnschnecke",
    16: "Nussschnecke",
    17: "Vanillehoernchen"
}

names_05 = {
    1: "Backware",
    2: "Bauernbrot",
    3: "Floesserbrot",
    4: "Salzstange",
    5: "Sonnenblumensemmel",
    6: "Kuerbiskernsemmel",
    7: "Roggensemmel",
    8: "Dinkelsemmel",
    9: "LaugenstangeSchinkenKaese",
    10: "Pfefferlaugenbrezel",
    11: "KernigeStange",
    12: "Schokocroissant",
    13: "Apfeltasche",
    14: "Quarktasche",
    15: "Mohnschnecke",
    16: "Nussschnecke",
    17: "Vanillehoernchen",
    18: "Osterei",
    19: "Osterbrezel",
    20: "Kirschtasche",
    21: "Fruechteschiffchen",
    22: "Anisbrezel",
    23: "Doppelsemmel",
    24: "Fruestuecksemmel",
    25: "Kaisersemmel",
    26: "Kornknacker",
    27: "Landbrot",
    28: "Laugenbrezel",
    29: "Laugenstange",
    30: "Laugenzopf",
    31: "Mohnsemmel",
    32: "Mohnstange",
    33: "Partybrot",
    34: "Sandwichbroetchen",
    35: "Sesamsemmel",
    36: "Sesamstange",
    37: "Vollgutsemmel"
}
